Update mutCovariate.indel.compile.R
changed  mut.freq = data.table::rbindlist(mut.freq,fill=TRUE)

from: https://www.rdocumentation.org/packages/data.table/versions/1.12.2/topics/rbindlist

use.names=TRUE binds by matching column name, FALSE by position. `check` (default) warns if all items don't have the same names in the same order and then currently proceeds as if `use.names=FALSE` for backwards compatibility (TRUE in future); see news for v1.12.2.

fill=TRUE fills missing columns with NAs. By default FALSE. When TRUE, use.names is set to TRUE.

Previously for some chromsomes not all contexts were present leading to errors e.g. 

Error in data.table::rbindlist(mut.freq) :
  Item 13 has 22 columns, inconsistent with item 1 which has 21 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.

In this case chr 10 (first globbed) had more fields than chr21 where "threeMerAAG" wasn't present. "fill=TRUE" 

> names(t21[[1]])
 [1] "subtypeEBV"     "subtypeGS"      "subtypeunknown" "cosmic1"
 [5] "cosmic17"       "ind.mut.count"  "mean_rep_time"  "local_mutrate"
 [9] "E094-H3K27ac"   "E094-H3K36me3"  "E094-H3K4me1"   "E094-H3K4me3"
[13] "POL2"           "SMC3"           "CTCF_boundary"  "oneMerA"
[17] "threeMerAAG"    "threeRightGA"   "threeLeftAA"    "threeLeftCA"
[21] "threeLeftCG"    "freq"
>
> names(t10[[1]])
Error: object 't10' not found
> names(t1[[1]])
 [1] "subtypeEBV"     "subtypeGS"      "subtypeunknown" "cosmic1"
 [5] "cosmic17"       "ind.mut.count"  "mean_rep_time"  "local_mutrate"
 [9] "E094-H3K27ac"   "E094-H3K36me3"  "E094-H3K4me1"   "E094-H3K4me3"
[13] "POL2"           "SMC3"           "CTCF_boundary"  "oneMerA"
[17] "threeLeftAA"    "fiveRightAGA"   "fiveRightAGT"   "threeRightAG"
[21] "freq"